name: Web

on: push

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch code
        uses: actions/checkout@v2

      - name: Setup nodejs environment
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Defines yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir.outputs.dir }}
            node_modules
            */*/node_modules
            ~/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Run lint
        run: yarn lint

      - name: Run unit tests
        run: yarn test --color
        env:
          CI: true
