name: Component Lib Storybook

on:
  push:
    paths:
      - 'packages/blog-components/**'
      - '.github/workflows/components-storybook.yml'

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install lerna and netlify
        run: yarn global add lerna netlify-cli

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Build storybook
        run: yarn build-storybook

      - name: Deploy Storybook docs to Netlify
        uses: nwtgck/actions-netlify@v1.1
        id: deploy
        with:
          publish-dir: storybook-static
          github-token: ${{ secrets.GITHUB_TOKEN }}
          production-branch: main
          deploy-message: 'Deploy from GitHub Actions - Storybook'
        env:
          NODE_ENV: production
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_COMPONENTS_STORYBOOK_SITE_ID }}
