name: Lambdas Deployment

on:
  push:
    paths:
      - 'apps/lambdas/**'
      - 'config/**'
      - '.github/workflows/lambdas.yml'
      - .eslintignore
      - .eslintrc.js
      - package.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install pnpm and netlify
        run: npm install -g netlify-cli pnpm

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile --filter lambdas...

      - name: Build Projects
        run: pnpm run build --filter lambdas...

      - name: Lint Projects
        run: pnpm run lint --filter lambdas

      - name: Test Projects
        run: pnpm run test --filter lambdas

      - name: Deploy
        run: pnpm run deploy --filter lambdas
        if: contains('refs/heads/main', github.ref)
        env:
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
          NETLIFY_SITE_ID: ${{secrets.LAMBDAS_SITE_ID}}
